apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    name: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
    - name: http
      containerPort: 8080
    - name: jnlp
      containerPort: 50000
    volumeMounts:
    - name: jenkins-home
      mountPath: /var/jenkins_home
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: jenkins-home
    emptyDir: {}
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: 8080
