
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: jenkins
  name: create-app
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-app-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins-serviceaccount
  namespace: jenkins
roleRef:
  kind: ClusterRole
  name: create-app
  apiGroup: rbac.authorization.k8s.io