apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
subjects:
- kind: ServiceAccount
  name: jenkins-serviceaccount
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io